### ISSUE TITLE
Can't rename Wireless patches with small width

### ISSUE THREAD

**Issue by jarmitage** [facebook/origami#62]
Following the tutorial at https://vimeo.com/120453305

When creating a Wireless patch (~7:30) and attaching it to the 'Up' interaction, it is impossible to rename it because the object is too small. It works fine for larger objects.

**Comment by tarngerine** [comment]
You can press the enter key to rename a patch when you've selected it. It's a convenient alternative to double clicking in these cases!






On Tue, Jan 12, 2016 at 2:52 AM -0800, "Jack Armitage" <notifications@github.com> wrote:












Following the tutorial at https://vimeo.com/120453305



When creating a Wireless patch (~7:30) and attaching it to the 'Up' interaction, it is impossible to rename it because the object is too small. It works fine for larger objects.
